### ISSUE TITLE
Ok to add IP address to sendTCP error messages?

### ISSUE THREAD

**Issue by draco2003** [cloudkucooland/go-kasa#2]
Working on debugging an issue where I occasionally get the new error after updating: 

Example: "not all bytes read: 1020/1144" ...snip all the data....

Unfortunately I have a large number of devices and when the error is thrown it's not easy to determine which device caused it. 
For this issue and future issuers it would be great to add the IP (or some other device identifying info) to errors in sendTCP if reasonable?  

https://github.com/cloudkucooland/go-kasa/blob/9fa0fc10f582816c08177e1da89bf1be502a33fc/net.go#L49

**Comment by cloudkucooland** [comment]
Yes, that's fine. Are you working with the most recent version? I've completely rewritten the network logic and it seems to be much better.

**Comment by cloudkucooland** [comment]
Ah, yes, that's in the new code. It looks like I need to do a small loop there to keep reading if not all bytes are read. I have never been able to trigger that block in my testing, but I might need to test with a small MTU or MSS. I'm swamped all day today, but might be able to get to it tomorrow.

**Comment by draco2003** [comment]
Currently running latest I believe ( github.com/cloudkucooland/go-kasa v0.0.0-20220324221805-9fa0fc10f582 ) 
I was getting unknown panics rarely, so decided to update prior to digging into that. After updating to the latest code, panics are gone, but the new error shows up ("not all bytes read: 1020/1144"). 
I will add the IP info to the logs via PR, and provide any additional details of the findings once I know more about what is causing it. Reproduction is slow on my side due to only impacting "production" about twice a day. Will be much easier to reproduce if/when I can isolate it to a device or two.

**Comment by cloudkucooland** [comment]
net.go line 44...

something like

totalRead = 0
for {
// allocate a second buffer, read into that instead
tmp = make ([]bytes, size)
	n, err = conn.Read(tmp)
	if err != nil {
		return nil, err
	}
        totalRead = totalRead + n
        if totalRead == size {
// move tmp into data io.copy probably
           break
        }
// for debugging
	if n != int(size) { 
		err := fmt.Errorf("not all bytes read: %d/%d, %s", n, size, data)
		klogger.Printf(err.Error())
		return nil, err
	}
        // move tmp into data at the correct offset io.copy
}

**Comment by cloudkucooland** [comment]
I was hoping to avoid extra copies and allocations, but it looks like I'll need to do one here.

**Comment by cloudkucooland** [comment]
> I was hoping to avoid extra copies and allocations, but it looks like I'll need to do one here.

Conn.Read can use data[n] to append to existing... save allocation and copy

**Comment by cloudkucooland** [comment]
Can you test this:

```
scot@covert:/home/scot/go-kasa % git diff
diff --git a/net.go b/net.go
index 241bf7c..e5f9159 100644
--- a/net.go
+++ b/net.go
@@ -41,14 +41,22 @@ func (d *Device) sendTCP(cmd string) ([]byte, error) {
        // we could leave the connection open and send subsequent requests
        // but for one-shot, this is enough
        data := make([]byte, size)
-       n, err = conn.Read(data)
-       if err != nil {
-               return nil, err
-       }
-       if n != int(size) {
-               err := fmt.Errorf("not all bytes read from host %s: %d/%d, %s", d.parsed, n, size, Unscramble(data))
-               klogger.Printf(err.Error())
-               return nil, err
+       totalread := 0
+       for {
+               n, err = conn.Read(data[totalread:])
+               if err != nil {
+                       return nil, err
+               }
+               totalread = totalread + n
+
+               if totalread < int(size) {
+                       err := fmt.Errorf("not all bytes read from host %s: %d/%d, %s", d.parsed, n, size, Unscramble(data))
+                       klogger.Printf(err.Error())
+                       // return nil, err
+               }
+               if totalread >= int(size) {
+                       break
+               }
        }
 
        return Unscramble(data), nil

```

**Comment by draco2003** [comment]
Based on the logs with the new format, it looks like they are all coming from a single device in my environment. 
I'm going to debug out all the sizes vs. read bytes to see if read bytes is always 1020 or less.

Additionally I might have a race condition where a setstate + get sysinfo call pair are happening simultaneously for each outlet on the 6 outlet powerstrip.

Will provide additional details as I dig into both of those threads.

**Comment by draco2003** [comment]
Sorry, got your update after my comment. I'll add that to my build and see how it works against the morning run.

**Comment by cloudkucooland** [comment]
If you are running multiple commands against a single device in fast order, I can build some logic for keeping the tcp connection open and using the single connection for the lifetime of the process (or a few minutes). In my normal use-case ( https://github.com/cloudkucooland/HomeKitBridges/tree/main/KasaHKBridge ) most of the calls are UDP. But it might be worth it to use a single TCP connection for serial commands.

**Comment by cloudkucooland** [comment]
```
diff --git a/net.go b/net.go
index 241bf7c..f41a53b 100644
--- a/net.go
+++ b/net.go
@@ -41,14 +41,19 @@ func (d *Device) sendTCP(cmd string) ([]byte, error) {
        // we could leave the connection open and send subsequent requests
        // but for one-shot, this is enough
        data := make([]byte, size)
-       n, err = conn.Read(data)
-       if err != nil {
-               return nil, err
-       }
-       if n != int(size) {
+       totalread := 0
+       for {
+               n, err = conn.Read(data[totalread:])
+               if err != nil {
+                       return nil, err
+               }
+               totalread = totalread + n
+
+               if totalread >= int(size) {
+                       break
+               }
                err := fmt.Errorf("not all bytes read from host %s: %d/%d, %s", d.parsed, n, size, Unscramble(data))
                klogger.Printf(err.Error())
-               return nil, err
        }
 
        return Unscramble(data), nil

```

**Comment by draco2003** [comment]
Let me test (unless you know?) to see if the CmdSetRelayStateChild allows me to set multiple child outlets at the same time or not by passing multiple child ids. 
If it does then I can do it in one command vs. multiple and wouldn't need a long lived connection. 

Usually if I don't have a scheduled event (sunset, sunrise, or other) than I only poll the devices every 5 minutes to make sure nothing has drifted from the desired state. 

Context:
https://github.com/cloudkucooland/go-kasa/blob/9fa0fc10f582816c08177e1da89bf1be502a33fc/consts.go#L25
https://github.com/cloudkucooland/go-kasa/blob/9fa0fc10f582816c08177e1da89bf1be502a33fc/commands.go#L37

**Comment by cloudkucooland** [comment]
> Let me test (unless you know?) to see if the CmdSetRelayStateChild allows me to set multiple child outlets at the same time or not by passing multiple child ids. If it does then I can do it in one command vs. multiple and wouldn't need a long lived connection.
> 
> Usually if I don't have a scheduled event (sunset, sunrise, or other) than I only poll the devices every 5 minutes to make sure nothing has drifted from the desired state.
> 
> Context:
> 
> https://github.com/cloudkucooland/go-kasa/blob/9fa0fc10f582816c08177e1da89bf1be502a33fc/consts.go#L25
> 
> 
> https://github.com/cloudkucooland/go-kasa/blob/9fa0fc10f582816c08177e1da89bf1be502a33fc/commands.go#L37

The Kasa protocol does support setting multiple child states in one go. I've never needed it, so not bothered to write a function for it. I don't recall where I read the format for the command. Let me dig a bit to find it.

**Comment by cloudkucooland** [comment]
{"context":{"child_ids":["00", "01", "02", "03", "04"]},"system":{"set_relay_state":{"state":1}}}

I'd make a CmdSetRelayStateChildMultiple  = `{"context":{"child_ids":[%s]},"system":{"set_relay_state":{"state":%d}}}` 

where the child_ids is built from a varargs passed into the function so function(false, "01", "02", "04")

gets built into the full format...

**Comment by cloudkucooland** [comment]
I've added SetRelayStateChildMulti(state, children...) completely without testing. Can you give it a try and see if it works as intended?

**Comment by draco2003** [comment]
Need to refactor my app a smidge to send all the childIDs vs. rapid fire individual childIDs. give me a few to switch that around and will confirm that it works with SetRelayStateChildMulti

**Comment by cloudkucooland** [comment]
How is the performance of the relays when you toggle multiple relays at once? Visible improvement over doing them serially?

**Comment by draco2003** [comment]
Do you have a reference/link to where you figured out the protocol? Seems like it's accepting the multi command now, but only changing the first element in the list when a list is provided.

**Comment by draco2003** [comment]
Created a group in the Kasa App, and hit the on/off and the all turn off at the same time. Going to see if I can get a copy of that traffic this weekend and compare what the app is sending vs. what the multi set is sending.

**Comment by cloudkucooland** [comment]
Building a test:

% kasa -d -c 01,02,03 switchmulti 192.168.12.173 true
2022/04/07 19:30:45 setting kasa hardware state for [192.168.12.173] to [true]
2022/04/07 19:30:45 relays ["01","02","03"]
2022/04/07 19:30:45 {"context":{"child_ids":["01","02","03"]},"system":{"set_relay_state":{"state":1}}}
2022/04/07 19:30:45 result [{"system":{"set_relay_state":{"err_code":-14,"err_msg":"entry not exist"}}}]

**Comment by cloudkucooland** [comment]
scot@covert:/home/scot/go-kasa % kasa -d -c 800661DA15771003D2531C57BE527BA61D9B40E400,800661DA15771003D2531C57BE527BA61D9B40E401,800661DA15771003D2531C57BE527BA61D9B40E402 switchmulti 192.168.12.173 true
2022/04/07 19:36:26 setting kasa hardware state for [192.168.12.173] to [true]
2022/04/07 19:36:26 relays ["800661DA15771003D2531C57BE527BA61D9B40E400","800661DA15771003D2531C57BE527BA61D9B40E401","800661DA15771003D2531C57BE527BA61D9B40E402"]
2022/04/07 19:36:26 {"context":{"child_ids":["800661DA15771003D2531C57BE527BA61D9B40E400","800661DA15771003D2531C57BE527BA61D9B40E401","800661DA15771003D2531C57BE527BA61D9B40E402"]},"system":{"set_relay_state":{"state":1}}}
2022/04/07 19:36:26 result [{"system":{"set_relay_state":{"err_code":0}}}]


using the full ID seems to work

**Comment by draco2003** [comment]
Can you share which hardware and firmware your device is running?

**Comment by cloudkucooland** [comment]
I've got 38 Kasa devices. The only ones which have multiple outlets are 3 KP303(US) used for fishtanks. I should pick up a bigger unit for the grow lights (and for testing).

scot@covert:/home/scot/go-kasa % kasa info 192.168.12.251
Alias:		Edgar
DevName:	
Model:		KP303(US) [1.0]
Device ID:	8006972A91D031658289D308866206E11D9B838A
OEM ID:		94E91A49D434FE323E91459A808F3460
Hardware ID:	FDE836D4DB9F379373AFE9BF3F5DCD2A
Software:	1.0.11 Build 210428 Rel.175849
MIC:		IOT.SMARTPLUGSWITCH
MAC:		84:D8:1B:90:2C:77
LED Off:	0
Active Mode:	
Outlet [Edgar Heater]:	1		(8006972A91D031658289D308866206E11D9B838A02)
Outlet [Edgar Bubbler]:	1		(8006972A91D031658289D308866206E11D9B838A01)
Outlet [Edgar Filter]:	1		(8006972A91D031658289D308866206E11D9B838A00)

**Comment by draco2003** [comment]
Using the CLI tool I get the same result with the 1 relay at a time despite sending multiple child ids. 
Current specs of that device is:

Model:          HS300(US) [2.0]
Software:       1.0.3 Build 201203 Rel.165457
MIC:            IOT.SMARTPLUGSWITCH

Going to see if I can free up one of the other hardware versions/software version devices and test/compare on that. 

Also I'm not seeing the results line while using the CLI so it might be returning an error but I'm not seeing it.

I (and the animals) greatly appreciate your support on this!

**Comment by cloudkucooland** [comment]
Make sure you are using the most recent CLI tool and the new switchmulti command...

kasa -c [long ID],[long ID] switchmulti [ip] [state]

I didn't commit the extended debugging from my above example. Change it from sendUDP to sendTCP and print out the result if you want to see what your device is returning.

**Comment by draco2003** [comment]
Did pull the latest changes. 
Updated the test device to the lastest firmware:
Software:       1.0.12 Build 220121 Rel.175814

Same results:
 ./main -d -c 80064DF5FCF2BC41171F9379A7517B561E7E868402,80064DF5FCF2BC41171F9379A7517B561E7E868403,80064DF5FCF2BC41171F9379A7517B561E7E868404,80064DF5FCF2BC41171F9379A7517B561E7E868405 switchmulti 192.168.2.36 false
2022/04/07 22:19:53 {"system":{"set_relay_state":{"err_code":0}}}

Says the command was successful, but only one relay was changed. 
Will see if it works the same or differently on the V3 hardware this weekend when I can move some plugs around.

**Comment by cloudkucooland** [comment]
I'm ordering an HS300 and a KS200M to add to my list of supported devices. It looks like the HS300 supports energy monitoring. I have rudimentary support for it since I have a KP115; this will give me a chance to see how multi-device support works.

**Comment by cloudkucooland** [comment]
<img width="745" alt="Screen Shot 2022-04-14 at 9 25 30 PM" src="https://user-images.githubusercontent.com/8037678/163508131-d0a42548-de31-4d92-b315-051572df7d30.png">

works easy-peasy in my HomeKit bridge

**Comment by cloudkucooland** [comment]
<img width="1440" alt="Screen Shot 2022-04-14 at 9 27 01 PM" src="https://user-images.githubusercontent.com/8037678/163508304-53ad5a9e-f551-4ee0-af4e-ad99e4e2deab.png">

**Comment by cloudkucooland** [comment]
Looks like I need to do some work on pulling emeter per plug; right now the cli only pulls the first plug (I've only had the kp115 until now). My LED grow lights are pulling 33w each (!!!) so being able to see usage will be nice for tracking the usage in the conservatory

**Comment by draco2003** [comment]
Great! Able to confirm/deny that sending multiple child_ids works for you on the strip? 

Getting the emeter data for the plugs would also be great for our setup/usage.

**Comment by cloudkucooland** [comment]
oh, I need to test multiple sends. Let me work on that today.

**Comment by cloudkucooland** [comment]
<img width="893" alt="Screen Shot 2022-04-15 at 10 34 16 AM" src="https://user-images.githubusercontent.com/8037678/163590347-bbb5fd7d-2877-4722-939e-2eb93f6fc9c1.png">

reading emeter data from child_ids

**Comment by cloudkucooland** [comment]
scot@covert:/home/scot/go-kasa % kasa -c "800663CD078A8C16B66658BEAA8D3F981EEF3EEA00,800663CD078A8C16B66658BEAA8D3F981EEF3EEA03,800663CD078A8C16B66658BEAA8D3F981EEF3EEA04,800663CD078A8C16B66658BEAA8D3F981EEF3EEA05" switchmulti 192.168.12.170 false ; kasa status  192.168.12.170
2022/04/15 10:41:55 {"context":{"child_ids":["800663CD078A8C16B66658BEAA8D3F981EEF3EEA00","800663CD078A8C16B66658BEAA8D3F981EEF3EEA03","800663CD078A8C16B66658BEAA8D3F981EEF3EEA04","800663CD078A8C16B66658BEAA8D3F981EEF3EEA05"]},"system":{"set_relay_state":{"state":0}}}


Only seems to change the first one. I'll have to dig into the protocol to see what I'm missing

**Comment by cloudkucooland** [comment]
https://github.com/p-doyle/Python-KasaSmartPowerStrip/blob/master/KasaSmartPowerStrip.py

I don't see what I'm doing differently; I'll keep looking

**Comment by cloudkucooland** [comment]
I'm guessing multi-child support is an unfinished feature in the devices:

scot@covert:/home/scot/go-kasa % kasa raw 192.168.12.170 '{"context":{"child_ids":["800663CD078A8C16B66658BEAA8D3F981EEF3EEA04","800663CD078A8C16B66658BEAA8D3F981EEF3EEA05"]},"emeter":{"get_realtime":{}}}'
2022/04/15 13:10:50 {"emeter":{"get_realtime":{"slot_id":4,"current_ma":0,"voltage_mv":124076,"power_mw":0,"total_wh":0,"err_code":0}}}


I can't get multiple emeter to work either.

scot@covert:/home/scot/go-kasa % kasa raw 192.168.12.170 '{"context":{"child_ids":["800663CD078A8C16B66658BEAA8D3F981EEF3EEA05","800663CD078A8C16B66658BEAA8D3F981EEF3EEA04"]},"system":{"set_relay_state":{"state":0},"get_sysinfo":{}},"emeter":{"get_realtime":{}}}'
2022/04/15 13:05:59 {"system":{"set_relay_state":{"err_code":0},"get_sysinfo":{"sw_ver":"1.0.12 Build 220121 Rel.175814","hw_ver":"2.0","model":"HS300(US)","deviceId":"800663CD078A8C16B66658BEAA8D3F981EEF3EEA","oemId":"32BD0B21AA9BF8E84737D1DB1C66E883","hwId":"955F433CBA24823A248A59AA64571A73","rssi":-62,"latitude_i":0,"longitude_i":0,"alias":"Plant Lights","status":"new","mic_type":"IOT.SMARTPLUGSWITCH","feature":"TIM:ENE","mac":"10:27:F5:8F:96:0E","updating":0,"led_off":0,"children":[{"id":"800663CD078A8C16B66658BEAA8D3F981EEF3EEA00","state":0,"alias":"Plant Heat Mat","on_time":0,"next_action":{"type":-1}},{"id":"800663CD078A8C16B66658BEAA8D3F981EEF3EEA01","state":1,"alias":"Plant Bench Light 1","on_time":9539,"next_action":{"type":-1}},{"id":"800663CD078A8C16B66658BEAA8D3F981EEF3EEA02","state":1,"alias":"Plant Bench Light 2","on_time":9539,"next_action":{"type":-1}},{"id":"800663CD078A8C16B66658BEAA8D3F981EEF3EEA03","state":0,"alias":"4","on_time":0,"next_action":{"type":-1}},{"id":"800663CD078A8C16B66658BEAA8D3F981EEF3EEA04","state":0,"alias":"5","on_time":0,"next_action":{"type":-1}},{"id":"800663CD078A8C16B66658BEAA8D3F981EEF3EEA05","state":0,"alias":"Sewing Machine","on_time":0,"next_action":{"type":-1}}],"child_num":6,"err_code":0}},"emeter":{"get_realtime":{"slot_id":5,"current_ma":0,"voltage_mv":124746,"power_mw":0,"total_wh":0,"err_code":0}}}

**Comment by draco2003** [comment]
Ok, that makes me feel better that I wasn't missing something. Bummer that it doesn't work the way we'd hoped it would.

**Comment by draco2003** [comment]
Hope all is well and again thanks for the great library.
