### ISSUE TITLE
Question on disable cloud command

### ISSUE THREAD

**Issue by theparkdude** [cloudkucooland/go-kasa#7]
If I disable cloud on my Kasa device, is there a way to re-enable it? I checked the commands.go file and did not see any additional cloud related commands. I'm trying to disable cloud services on a HS220 dimmer switch but would like to be able to revert back if needed.

**Comment by cloudkucooland** [comment]
I don't have a command built for it in this tool (I've never needed it), but it would take just a minute or two to add it.

{"cnCloud":{"bind":{"username":"alice@home.com", "password":"secret"}}}

**Comment by theparkdude** [comment]
OK great, can I request it be added to the tool? Thank you.

**Comment by cloudkucooland** [comment]
Please test https://github.com/cloudkucooland/go-kasa/commit/034aad4bebda5f317dff03182e29ee80b61f025f
```
kasa cloud 192.168.12.216 "testing@test.com" "password123"
```

**Comment by theparkdude** [comment]
Works great, I confirmed in the Kasa app my device is showing again after having been removed and it's nice to know I can revert back if needed. Thanks for getting that added, appreciate it!
